[package]
name = "ov-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
ov-core = { path = "../ov-core" }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
